services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/ecom_store
      JWT_SECRET: your_jwt_secret_key
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecom_store
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

volumes:
  db_data:
